### ISSUE TITLE
Create the plugin banner for WordPress.org

### ISSUE THREAD

**Issue by jonathanbardo** [xwp/wp-mentionable#1]
Any ideas are welcome!

**Comment by jonathanbardo** [comment]
What about something really simple like this :

![banner](https://f.cloud.github.com/assets/1933681/1372705/55295e1c-3a56-11e3-9ca7-a184eba232d6.png)

/cc @westonruter @fjarrett

**Comment by gedex** [comment]
@jonathanbardo Looks nice to me. It describes what this plugin offers.

**Comment by johnregan3** [comment]
This image does say much more than a big block of text would.  In the open area on the right, I'd add a little explanation of what it does (like, "@mention any content from inside your posts"). Also, I know @westonruter likes to include the x-team logo somewhere, like maybe in the lower right corner.  

Just some ideas.  I think this is a great start! @jonathanbardo

**Comment by westonruter** [comment]
@jonathanbardo maybe the auto-completed text should be more true to a real use case, for example:

> Wow. Time flies! This is our 100th post. Go back and time and check out our first post, @[AUTOCOMPLETE HERE]

**Comment by frankiejarrett** [comment]
I'm not a huge fan of using screenshots as the banner image since that is what the **Screenshots** tab should be for.

**Comment by johnregan3** [comment]
I think just once we should use this as the banner image: http://images.wikia.com/revengeristsconsortium/images/0/0f/Dinosaurs_Lasers.jpg

**Comment by westonruter** [comment]
But the screenshots tab is too far away. It seems like to hook someone in
to the plugin they should be able to see as soon as possible what they are
actually going to get.

**Comment by jonathanbardo** [comment]
I like the dinosaurs @johnregan3 !

**Comment by jonathanbardo** [comment]
Here is another attempt going in the same direction with the feedback added from @westonruter and @johnregan3.
![wordpress__force_featured_image__wordpress_plugins-5](https://f.cloud.github.com/assets/1933681/1468250/b7f291d2-458f-11e3-9f10-e8a89f8e9c54.png)

I hate the vignetting WordPress directory puts inside the image... but what can we do...

**Comment by gedex** [comment]
@jonathanbardo Looks good on the top, but the description below the post editor is about force featured image?

> Ever wanted to force a user to publish a post with a featured image of a certain dimension? ...

**Comment by westonruter** [comment]
Perfect!

**Comment by jonathanbardo** [comment]
@gedex Yes I know... it was only to show context on this one!
