### ISSUE TITLE
Add possibility to mention user

### ISSUE THREAD

**Issue by jonathanbardo** [xwp/wp-mentionable#16]

**Comment by nash-ye** [comment]
I want to help on this plugin, let this task for me :)

**Comment by nash-ye** [comment]
Can you create a develop branch for this plugin?

**Comment by jonathanbardo** [comment]
Of course !

**Comment by nash-ye** [comment]
Sorry for the delay, I have push the commit `f18c8374da134e1f0efa5cc1d082c2b270662076` You have only to change the `autocomplete_object_type` to `user` in the options array.

I will add the option to the plugin settings page now.
