### ISSUE TITLE
Create a settings page to choose mentionable post types

### ISSUE THREAD

**Issue by jonathanbardo** [xwp/wp-mentionable#2]
A simple way to achieve this would be to put a dropdown list with select2.js multiple select.

**Comment by shadyvb** [comment]
@jonathanbardo Can we add those two fields to the WP Settings page ? Since we'll probably not have many fields to add, so having a new admin page wouldn't be much needed. What do you think ?

**Comment by jonathanbardo** [comment]
@shadyvb I think you are right! Maybe we could put this under another section already in WordPress.

**Comment by gedex** [comment]
In addition to choose mentionable post type is to choose the source of post type that can be mentioned in particular post type (in form of multiple select).

**Comment by shadyvb** [comment]
Since we're already having expansion plans ( modules, media/attachment inclusion ) i think a dedicated page will be needed sooner or later. Hence my last commit.

**Comment by shadyvb** [comment]
@jonathanbardo Reassigned for review.
