### ISSUE TITLE
Create a admin settings field to do custom html replacement

### ISSUE THREAD

**Issue by jonathanbardo** [xwp/wp-mentionable#4]
This requires issue #2 to be completed

**Comment by jonathanbardo** [comment]
Something like this might be useful : 

``` php
add_filter( 'the_content', function ( $content ) {
    $content = preg_replace_callback( '#<a [^>]+*?data-mentionable[^>]+>.*?</a>#', 'handle_replacement_for_mentionable', $content );
    return $content;
} );
```

**Comment by shadyvb** [comment]
@jonathanbardo So the inserted html should stay intact, but have another function tweak the output based on html template added by the user ?

While this is pretty clever to ensure the consistency of content, i think there is a good amount of overhead here doing regex replacement.

What if we let the user choose ? whether to:
- apply the new template to all old posts, and newer posts as well ( lets js use the new template from now on )
- replace content on the fly and keep db consistent

**Comment by jonathanbardo** [comment]
I don't think this will generate that much overhead since we are doing a simple find and replace (like a shortcode would do). What do you think @westonruter?

**Comment by westonruter** [comment]
@jonathanbardo @shadyvb yeah, I'm not concerned with this regex.
