### ISSUE TITLE
Adds post meta to store how many times a post is mentioned

### ISSUE THREAD

**Issue by gedex** [xwp/wp-mentionable#6]

**Comment by jonathanbardo** [comment]
This should be done on save by filtering the post content. We have to make sure we remove follow the count number if the mention is removed on save. 

It would be nice to also store mention inside post metas as we would be able to do a meta query and get all post that mention a specific post.

**Comment by gedex** [comment]
@jonathanbardo Brilliant idea! There are so much features can be added when this one implemented, for instance a widget that list posts mentioning current post and vice versa.

**Comment by westonruter** [comment]
Given that meta_query is slow, what about utilizing P2P if the plugin is
active? Can there be private connections registered?

**Comment by jonathanbardo** [comment]
We can try to look into that!

**Comment by topher1kenobe** [comment]
@westonruter  If this is meant for general release, is it safe to count on P2P?  Or were you thinking we'd look for it and use it if it's there, else fall back to the options table, a la transients?

**Comment by westonruter** [comment]
Yeah, we wouldn't count on P2P, but we'd integrate with it if it was activated.
