### ISSUE TITLE
Adds button in post editor

### ISSUE THREAD

**Issue by gedex** [xwp/wp-mentionable#7]
It would be nice to have a button in post editor that upon clicked will popup a list of mentionable posts (with, optionally, search box). When the post, from the list, is clicked it will bring the shortcode into the editor.

**Comment by jonathanbardo** [comment]
We thought about using shortcode with @fjarrett and @westonruter and we finally ruled them out in favour of a simple anchor tag that we would replace by filtering the post content. 

Is the popup list you are proposing any different than the one WordPress already include?

**Comment by gedex** [comment]
Yeah, the popup should be similar to current 'Insert/edit link' dialog. But it will bring the mention shortcode to post editor instead of a link.

**Comment by jonathanbardo** [comment]
I think we can have another discussion about it, but the plugin in my opinion shouldn't use shortcode because they are hard to remove if the plugin is deactivated. If we use a simple anchor tag we can replace and the user wants to deactivate de plugin, all anchor would be all still valid.

**Comment by gedex** [comment]
Ah, I didn't read your comment carefully that shortcode wasn't used. Sorry about that :).

**Comment by shadyvb** [comment]
@gedex Should this issue be closed ?

**Comment by gedex** [comment]
@shadyvb Yes. Thanks remind me.
