### ISSUE TITLE
Change localization for new 3.7 language pack.

### ISSUE THREAD

**Issue by jonathanbardo** [xwp/wp-mentionable#8]
See http://ottopress.com/2013/language-packs-101-prepwork/

**Comment by westonruter** [comment]
@jonathanbardo I would also expect a `fr-CA` language pack from you, sir :wink:

**Comment by topher1kenobe** [comment]
I've been reading up on what's involved with this, and it looks for all the world like this is already done.  These are already in the header:
- Text Domain: mentionable
- Domain Path: /languages

and the function i18n is already calling the path to language files.

Am I missing something, or did someone already do this?

@jonathanbardo

**Comment by jonathanbardo** [comment]
I will translate this into french to make sure this is working properly.
